### ISSUE TITLE
Issue While running train.py

### ISSUE THREAD

**Issue by hasam6400** [yjlolo/vae-audio#3]
Hello,
I'm trying to run your code but I am getting errors.
when I run the following command, I get the error:

python train.py -c config_gmvae.json
Traceback (most recent call last):
  File "train.py", line 58, in <module>
    main(config)
  File "train.py", line 17, in main
    data_loader = config.initialize('data_loader', module_data)
  File "/home/hasam/Documents/vae-audio-master/parse_config.py", line 61, in initialize
    return getattr(module, module_cfg['type'])(*args, **module_cfg['args'])
  File "/home/hasam/Documents/vae-audio-master/data_loader/data_loaders.py", line 57, in __init__
    self.dataset = NsynthSubset(self.data_dir, file_ext='.npy', transform=self.transform, **kwargs)
  File "/home/hasam/Documents/vae-audio-master/dataset/datasets.py", line 90, in __init__
    raise Warning("The size of path_to_data is zero with the specified extension %s" % file_ext)
Warning: The size of path_to_data is zero with the specified extension *.npy

And same with this config file:

python train.py -c config.json

Traceback (most recent call last):
  File "train.py", line 58, in <module>
    main(config)
  File "train.py", line 21, in main
    model = config.initialize('arch', module_arch)
  File "/home/hasam/Documents/vae-audio-master/parse_config.py", line 61, in initialize
    return getattr(module, module_cfg['type'])(*args, **module_cfg['args'])
  File "/home/hasam/Documents/vae-audio-master/model/model.py", line 121, in __init__
    self.n_freqBand, self.n_contextWin = input_size
ValueError: too many values to unpack (expected 2)

Can you please tell me what I'm doing wrong?

**Comment by CYP0630** [comment]
Hello, 
  I have the same problem. Had you solved this problem?

**Comment by magnusgp** [comment]
It seems like the input_size is set wrong in the model architecture in config.json. 
I changed it from [1, 64, 15] to [64, 15] in order to make it comply with the VAE architecture.

Here's my modified config.json:

```
{

    "name": "SpecVAE",
    "n_gpu": 1,
    "arch": {
        "type": "SpecVAE",
        "args": {
            "input_size": [64, 15],
            "latent_dim": 32,
            "is_featExtract": false,
            "n_convLayer": 3,
            "n_convChannel": [32, 16, 8],
            "filter_size": [1, 3, 3],
            "stride": [1, 2, 2],
            "n_fcLayer": 1,
            "n_fcChannel": [256]
        }
    },
    "data_loader": {
        "type": "CollectDataLoader",
        "args":{
            "data_dir": ["dataset/myAudioDataset/m64-5s"],
            "batch_size": 32,
            "shuffle": true,
            "validation_split": 0.1,
            "num_workers": 0,
            "subset": "train"
        }
    },
    "optimizer": {
        "type": "Adam",
        "args":{
            "lr": 0.005,
            "weight_decay": 0.0001,
            "amsgrad": true
        }
    },
    "loss": "vae_loss",
    "metrics": [
        "my_metric", "my_metric2"
    ],
    "lr_scheduler": {
        "type": "StepLR",
        "args": {
            "step_size": 50,
            "gamma": 0.1
        }
    },
    "trainer": {
        "type": "SpecVaeTrainer",
        "epochs": 1000,

        "save_dir": "saved/",
        "save_period": 10,
        "verbosity": 2,
        
        "monitor": "min val_loss",
        "early_stop": 40,
        
        "tensorboardX": true
    }
}
```
